FROM node:18-alpine

WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm install

# Copy app source code
COPY . .

EXPOSE 3000

CMD ["npm", "start"]